<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE book [
    <!ELEMENT book (title, author, isbn, publisher, edition, price)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT ISBN (#PCDATA)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT edition (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>

<bookstore>
    <book stream="Ctech">
        <title>Computer Science and Application</title>
        <author>Dave Thomas</author>
        <price>â‚¹3,489.00</price>
        <ISBN>876-09-98765-02-5</ISBN>
        <publisher>SIA Publishers</publisher>
    </book>    
    <book stream="IT">
        <title>Making IT Count</title>
        <author>Leslie P. Willcocks</author>
        <price>15,456</price>
        <ISBN>986-49-98355-01-2</ISBN>
        <publisher>Routledge; 1st edition</publisher>
    </book>
    <book stream="ETC">
        <title>ELECTRONIC DEVICES AND CIRCUIT THEORY</title>
        <author>Robert L. Boylestad</author>
        <price>Rs.935</price>
        <ISBN>978-9332542600</ISBN>
        <publisher>Pearson Education India; 11th edition</publisher>
    </book>   
    <book stream="CIVIL">
        <title>WATER RESOURCES ENGINEERING </title>
        <author></author>
        <price>Rs.200</price>
        <ISBN>978-9388897839</ISBN>
        <publisher>Nirali Prakashan</publisher>
    </book>
    <book stream="MECHANICAL">
        <title>Refrigeration And Air Conditioning</title>
        <author>C P Arora</author>
        <price>Rs.817</price>
        <ISBN>978-9390385843</ISBN>
        <publisher>McGraw Hill;</publisher>
    </book>


</bookstore>