<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE EMPLOYEES[
<!ELEMENT EMPLOYEES (EMPLOYEE+)>
<!ELEMENT EMPLOYEE (NAME, SALARY, POSITION, WORKINGDAYS)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT SALARY (#PCDATA)>
<!ELEMENT WORKINGDAYS (#PCDATA)>
<!ELEMENT POSITION (#PCDATA)>
]>

<EMPLOYEES>
<EMPLOYEE>
	<NAME>DARSHAN BAGADE</NAME>
	<SALARY>1000000</SALARY>
	<POSITION>CTO</POSITION>
	<WORKINGDAYS>5</WORKINGDAYS>
</EMPLOYEE>
<EMPLOYEE>
	<NAME>DAVID DESHMUKH</NAME>
	<SALARY>500000</SALARY>
	<POSITION>CFO</POSITION>
	<WORKINGDAYS>5</WORKINGDAYS>
</EMPLOYEE>
<EMPLOYEE>
	<NAME>ARCHIT GULHANE</NAME>
	<SALARY>250000</SALARY>
	<POSITION>PRODUCT MANAGER</POSITION>
	<WORKINGDAYS>7</WORKINGDAYS>
</EMPLOYEE>
<EMPLOYEE>
	<NAME>VAIBHAV DHYANI</NAME>
	<SALARY>300000</SALARY>
	<POSITION>CSO</POSITION>
	<WORKINGDAYS>5</WORKINGDAYS>
</EMPLOYEE>
<EMPLOYEE>
	<NAME>HARISH JAJU</NAME>
	<SALARY>1000000</SALARY>
	<POSITION>Finacial Manager</POSITION>
	<WORKINGDAYS>5</WORKINGDAYS>
</EMPLOYEE>

</EMPLOYEES>