=== darshanbagade/CollegeRepo/Web Technology/Practical Program/5-B-DTD.dtd
<!ELEMENT BOOKS (BOOK+)>
<!ELEMENT BOOK (NAME, AUTHOR, ISBN, PRICE, PUBLISHER)>
<!ELEMENT NAME (#PCDATA) >
<!ELEMENT AUTHOR (#PCDATA) >
<!ELEMENT ISBN (#PCDATA) >
<!ELEMENT PRICE (#PCDATA) >
<!ELEMENT PUBLISHER (#PCDATA) >

=== darshanbagade/CollegeRepo/Web Technology/Practical Program/5-B-ExternalDTDXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BOOKS SYSTEM "5-B-DTD.dtd" >
<BOOKS>
<BOOK>
	<NAME>THE PRAGMATIC PROGRAMMER</NAME>
	<AUTHOR>DANIS LARY</AUTHOR>
	<ISBN>123-66665N1123</ISBN>
	<PRICE>USD.30</PRICE>
	<PUBLISHER>KARAN EMYEE</PUBLISHER>
</BOOK>
<BOOK>
	<NAME>PROGRAMMIN IN C++</NAME>
	<AUTHOR>STRSHTRUP</AUTHOR>
	<ISBN>1111234345-34</ISBN>
	<PRICE>USD.49</PRICE>
	<PUBLISHER>VIJAY PICHAI</PUBLISHER>
</BOOK>
<BOOK>
	<NAME>THE PRAGMATIC PROGRAMMER</NAME>
	<AUTHOR>DANIS LARY</AUTHOR>
	<ISBN>123-66665N1123</ISBN>
	<PRICE>USD.30</PRICE>
	<PUBLISHER>KARAN EMYEE</PUBLISHER>
</BOOK>
<BOOK>
	<NAME>PROGRAMMIN IN C++</NAME>
	<AUTHOR>STRSHTRUP</AUTHOR>
	<ISBN>1111234345-34</ISBN>
	<PRICE>USD.49</PRICE>
	<PUBLISHER>VIJAY PICHAI</PUBLISHER>
</BOOK>
</BOOKS>
